services:
  backend:
    build: ./back
    container_name: accident-backend
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app
    environment:
      - PYTHONUNBUFFERED=1

  ia-service:
    build:
      context: ./ia
      dockerfile: Dockerfile
    container_name: accident-ia
    ports:
      - "8080:8080"
    volumes:
      - ./ia/model:/app/model
    environment:
      - PYTHONUNBUFFERED=1